//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.InvestmentDetails = new HashSet<InvestmentDetail>();
            this.InvestmentDetails1 = new HashSet<InvestmentDetail>();
            this.InvestmentDetails2 = new HashSet<InvestmentDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Relationship { get; set; }
        public string AadharNo { get; set; }
        public string PANNo { get; set; }
        public string LandlineNo { get; set; }
        public string CellNo { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Family Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentDetail> InvestmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentDetail> InvestmentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentDetail> InvestmentDetails2 { get; set; }
    }
}
