//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheme()
        {
            this.InvestmentDetails = new HashSet<InvestmentDetail>();
            this.SchemeDetails = new HashSet<SchemeDetail>();
        }
    
        public int ID { get; set; }
        public string Scheme1 { get; set; }
        public string Description { get; set; }
        public int InterestCalculationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvestmentDetail> InvestmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchemeDetail> SchemeDetails { get; set; }
    }
}
